#!/usr/bin/env python3
"""Bake the MTA station directory into apps/nyc-subway/app.py.

Source: tools/data/Stations.csv — the official MTA stations file
(web.mta.info/developers/data/nyct/subway/Stations.csv, mirrored on
data.ny.gov). Emits STATIONS_B64 between codegen markers: zlib+base64 of
minified JSON rows

    [gtfs_stop_id, stop_name, daytime_routes, north_label, south_label]

Direction-suffixed platform ids are formed at runtime (R23 + N -> R23N).

    python3 tools/build_stations.py            # rewrite app.py
    python3 tools/build_stations.py --fetch    # re-download the CSV first
"""
import argparse
import base64
import csv
import json
import re
import sys
import textwrap
import urllib.request
import zlib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
APP = ROOT / "apps" / "nyc-subway" / "app.py"
CSV_PATH = ROOT / "tools" / "data" / "Stations.csv"

SOURCES = (
    "http://web.mta.info/developers/data/nyct/subway/Stations.csv",
    "https://data.ny.gov/api/views/39hk-dx4f/rows.csv?accessType=DOWNLOAD",
)

# tolerate both the legacy header set and data.ny.gov's re-cased one
COLS = {
    "stop_id": ("GTFS Stop ID", "gtfs_stop_id"),
    "name": ("Stop Name", "stop_name"),
    "routes": ("Daytime Routes", "daytime_routes"),
    "north": ("North Direction Label", "north_direction_label"),
    "south": ("South Direction Label", "south_direction_label"),
}


def fetch() -> None:
    for url in SOURCES:
        try:
            with urllib.request.urlopen(url, timeout=60) as r:
                blob = r.read()
            if b"Stop Name" in blob[:400] or b"stop_name" in blob[:400]:
                CSV_PATH.write_bytes(blob)
                print(f"fetched {len(blob)} bytes from {url}")
                return
        except OSError as e:
            print(f"{url}: {e}", file=sys.stderr)
    raise SystemExit("could not fetch Stations.csv from any source")


def load_rows() -> list[list[str]]:
    with CSV_PATH.open(newline="") as f:
        reader = csv.DictReader(f)
        headers = reader.fieldnames or []

        def col(key: str) -> str:
            for cand in COLS[key]:
                for h in headers:
                    if h.strip().lower() == cand.lower():
                        return h
            raise SystemExit(f"column for {key!r} not found in {headers}")

        cols = {k: col(k) for k in COLS}
        rows = []
        for rec in reader:
            stop_id = rec[cols["stop_id"]].strip()
            if not stop_id:
                continue
            rows.append([
                stop_id,
                rec[cols["name"]].strip(),
                rec[cols["routes"]].strip(),
                rec[cols["north"]].strip(),
                rec[cols["south"]].strip(),
            ])
    if len(rows) < 400:
        raise SystemExit(f"only {len(rows)} stations parsed — wrong file?")
    return rows


def replace_marker(src: str, name: str, body: str) -> str:
    begin = f"# --- BEGIN GENERATED: {name} ---"
    end = f"# --- END GENERATED: {name} ---"
    pattern = re.compile(re.escape(begin) + r".*?" + re.escape(end), re.S)
    if not pattern.search(src):
        raise SystemExit(f"marker {name} not found in {APP}")
    stamp = f"{begin}\n# generated by tools/build_stations.py — do not edit by hand\n{body}\n{end}"
    return pattern.sub(lambda _: stamp, src)


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--fetch", action="store_true")
    args = ap.parse_args()
    if args.fetch or not CSV_PATH.exists():
        fetch()

    rows = load_rows()
    packed = zlib.compress(
        json.dumps(rows, separators=(",", ":")).encode(), 9)
    enc = base64.b64encode(packed).decode()
    body = ("STATIONS_B64 = (\n"
            + "\n".join(f'    "{ln}"' for ln in textwrap.wrap(enc, 68))
            + "\n)")
    APP.write_text(replace_marker(APP.read_text(), "STATIONS", body))
    routes = sorted({r for row in rows for r in row[2].split()})
    print(f"wrote STATIONS: {len(rows)} stations, {len(packed)} bytes packed "
          f"({len(enc)} b64); routes seen: {' '.join(routes)}")


if __name__ == "__main__":
    main()
